#!/bin/sh
# <UDF name="hostname" Label="hostname for this host" example="testing.rusa.org" />

exec > /tmp/stack-script.log 2>&1
set -x

# This sets the variable $IPADDR to the IP address the new Linode receives.
IPADDR=$(/sbin/ifconfig eth0 | awk '/inet / { print $2 }' | sed 's/addr://')

# This updates the packages on the system from the distribution repositories.
apt-get update
apt-get upgrade -y

# This section sets the hostname.
echo $HOSTNAME > /etc/hostname
hostname -F /etc/hostname

# This section sets the Fully Qualified Domain Name (FQDN) in the hosts file.
echo $IPADDR $FQDN $HOSTNAME >> /etc/hosts

apt-get install -y git puppet

mkdir /opt
cd /opt
git clone https://github.com/RandonneursUSA/rusa.git

cd /opt/rusa/puppet
./run_puppet.sh

# cd /opt/rusa/misc
# ./build-emacs24.sh
